import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;


/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '5/8/15 6:18 PM' with Gradle 2.2.1-20150128190215+0000
 *
 * @author ltudor, @date 5/8/15 6:18 PM
 */
public class Library {
    public static void main(String args[]) {
        int threads = 5;
        int tasks = 100;
        int wait = 100;
        ExecutorService exec = Executors.newFixedThreadPool(threads, new NamedThreadFactory("LivTest"));

        for (int i = 0; i < tasks; i++) {
            System.out.println("Submitting " + i);
            exec.submit(new DummyRunnable());
        }

        System.out.println(exec.toString());

        for (int i = 0; i < wait; i++) {
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        System.out.println(exec.toString());

        exec.shutdown();
    }
}
